### ISSUE TITLE
[BE] 이밴트 API 서비스 개발

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-alarm#1]
## **✏️ Feature 작업**
이벤트 API 서비스 개발

## **✅ TO-DO** 
- [x] 이벤트 게시글 조회
- [x] 이벤트 게시글 등록
- [x] 이벤트 게시글 삭제
- [x] 이벤트 게시글 수정
- [x] 이벤트 게시글 리스트 조회 (페이징)

## **🚨 주의사항** 
✔️ 이미지 서버 연동 필요
