### ISSUE TITLE
[BE] 알림 서비스 전체 리팩토링

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-alarm#8]
## **✏️ Feature 작업**
알림, 공지, 이벤트 서비스 리팩토링 및 필요 기능 수정

## **✅ TO-DO** 
- [x] 알림 서비스 리팩토링
- [x] 공지 서비스 리팩토링
- [x] 이벤트 서비스 리팩토링
- [x] 읽음 처리 여부 로직 추가 
- [ ] 공지, 이벤트의 title 수정 시 알림 detail 변경 수정

## **🚨 주의사항** 
✔️ 주의 사항
